language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: VqNWUsTwrhVkcH+o80iA2tvPV3FAMOA6zWtnTxKRYxTVyrlZ/P61KwipUzRQSsmUuZ/4xZQfU3V6DpOeaMWTZtvV93wCVDTh5R3SwbIbVdq0mbHZbDY59BDEE2PcZZOyxNeVzqkpfBZfpCYqgXNPSPxZDvdd1trfK49DFTBcpKIB+dXXjzeZs8RdEmE83LzuLB/R2SkCTa45RMshd11W1NQrrcFLZibt2MpAA4Q9452auypnl4qcC7yeBtXO7nZTyOgaPf0vPCvpb7KDjII3G9j7TjW958Zmr/D+cBq1sRSs5oMvUellMFi5vtB99OK6pTQ1Ikw7JaKeDB5tcS3kKckkgKyg41gJZuosDHUCtBBbmldczaOh4B2rxGdXJgo0/+QepQgHi/DFtD4fnkmO3g7V6wLmvEvl/c6MwKyOHj8LWi14FJuDAQlbS7SlKwXBLy2s+/sVaxlvywrltFlBYzmqJGDOc3MdxSMqxc2lCwC7Pzly+8bIjqkwYPvKRoOrCKRAsj5VfjfUyrOpnnPJ7BCGndcAi/HZlAC2EGQ4QE8xDsMv90l4sO4XQjovmIrgVIayaL0ZU0+MtIwTYqjUgEHcqYT/QsQ+7bqnukRSfZ4YpXQ5EZX87lG3ng4PB2T6HEJO4xUJIoJmsat8k678mU4HrK/B4KlXe5UH/x5rNH8=
  - secure: Zp0Cco5HghBiXBpijMmSZDzA65v/ngX5439tone4sMV485tHi55ZILMZ4n4T8eJESYlLY/nWQCNiYIKY7X3cSC/8Nv5PozY2ks+oocJsYc6zG+2cCqauFaWG293eY5qdQo9YHkmlIEU2DtCo1HhlF1zNFLMmn305Avn+vo+JDrtbnS/CiWxbfpf9EMprLF4KRoayyvECcpefbFlhL1Lmft9XfESw3+bvzUnFRgI94ioL5p1dejK0WgTxAafR7Ybz3TYaP9C7ddjYUBd76J9+TNn9oV3eKoc92D9N6xEO9Td07mgqJ9scCqjhr69i+ttBhVbTfucpoXNqNWBjCub8J7x+GXZJpZMJvUq2XPWP1Wx7IS6yye8sQTZqH0nJUa8QwwJP/Xib21sovTj+mr373cDVutOlKmRu4aH8w1cOWpIngyDaiEP7YeFfiaYTf//qhmCA66u3XOvqktJ+Gh6sxItZXlIFMYTOTtpCioKM0BWyMgh21eMYiDvk2r+Z1FPl4sLC9fQZljQ6Z2z+5DBgM9h7rbzJ29088kJRIe5AxRbBNu5n41lYUlmFyH5GRWY1qvq/+QEniEBEcsB5uvlIkY88yi21pyi8dZOo/c616EmorwFb6d1wgh5KGKtGDAUkSm7NL+u5lBlCgMYNEXyVeKei40VBu7SrFFLemuzbeP0=
