language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: WY+CTSZOXiCIr+qXjva6MxxXa8MyOLVRaY7BpYKvdU+Ld/fLz5COn5UC/K/4DohuUorz8woV4sc02rHLuZCsXWtdWilix0y5o2mdzHg+d8vZPp7tH7fAWGDNaWmr2bYm1UJVs3SDuhXpG/BiiJxgPdgZWGp3SkGXjY+jsm3ZMgJMqkCNM+d42mGGRnVs4RkZA5HFS7PFJ59cmF1w6h1x5/74d18PGe919OA9+cIaYXtso+ObIfuyu51Any/kH04EHeh6125e+mL6M7ayHHED4kXYs0aDhLr8HNMgJi0KqlxYgOApIa6UW90COmInzClSYispAuD2NzAw9doJATR0T07RXA7v+PsifnGx7bPB+nKecZHQss59IjJZ1zk2o+QSMrOde2i19WcZMd9d4YvNFIr5wXxa6tlV5lAFLJgDNCz9pdskCFKTHqcrdtX9gKESeb7v1bxyM/h5og02DijDOaYiBVFCsowi4O4keqFIMFRbvVRVDAB0LuxK1TbtiJUqBQngBMARK5gCvOjHJ1HUg7EUESsk4j6rjnwAt5t8N/c8H+VsIxeJgwmWYZ4k31jNqN5C5e/C02QNfJ2BNZeHSK5vAbfgH59yIjEcCgu9BQjIdjOZI5zxEeTrWCtapfu2N+I3886RUIpbcqiE76vE1SaKSAwQ8I01u0eCaB1VP+s=
  - secure: vA4oXVSyl27/1qH48yGQAJADMznF8fYcDkYR3dsXlVs23IipiwzNYE43jvcUM16D9fq+Tf8IO8glKcsadaXIJTmOYLsQhYao9qXub3bR3gHGZ4r08ow03QJykfFL75EbO7KXu1YYnoCWG3bSFIfi+6/xC9R0GAJYCBOtazuni1GzGPYz+UD9oecKqpEbSsAz+rPT2AQKpDpKeYXjM2i8PjqwihvBWGUrpH1db4bpTt0qruJfMcNllxUyB/yh8jthKvLRWdq2guLq98KLJowE/BQNiICsEcK4C1LzbRd4kwgQZCZpspdVe+rACy8hkjweOzBwAf5I1gMT+dONsnunYlp09rH1AKUErW47iIAmTuKs3ObH9HKLZa3hQDRMjZPqIvM23DcqG7fFz27rrbTIeSvsKgrVO6Gc69nrjpUIl262+VDICmVFI9uoatf5IkRXKKZsgOF1fdL4/NxEJOnHVrxGFIOJUzHTZoq5PNyX26IHNk1t3kFYQ2sgnKC9e1YKauKUXkiB9HWg6gXXGv6eaWhQukwVmVtDE9zElIuLcHA854pBjmig5+PuFK4zr+ljkMLelAUScnmrOEHnJ0CPGa158HeNYyoxAefLUMv5/04tzMYSuIwfYh3UHRnlGice3QwAc5fbA4+XXr9aH0rfFgH6EZuASj218KGMaLJor1U=
